// This file is auto-generated by scripts/generate-models.ts — do not edit manually.
// Run `bun run scripts/generate-models.ts` to regenerate from https://api.neuralwatt.com/v1/models
import type { ProviderModelConfig } from "@earendil-works/pi-coding-agent";

export const NEURALWATT_MODELS: Record<string, ProviderModelConfig> = {
  "qwen3.6-35b": {
    id: "qwen3.6-35b",
    name: "Qwen3.6 35b (NW Fast)",
    reasoning: true,
    compat: {
      "supportsReasoningEffort": false,
      "supportsDeveloperRole": false
    },
    input: [
      "text"
    ],
    contextWindow: 131056,
    maxTokens: 32768,
    cost: {
      "input": 0.29,
      "output": 1.15,
      "cacheRead": 0.0725,
      "cacheWrite": 0
    },
  },
  "qwen3.6-35b-fast": {
    id: "qwen3.6-35b-fast",
    name: "Qwen3.6 35b Fast (NW Fast)",
    reasoning: false,
    compat: {
      "supportsDeveloperRole": false
    },
    input: [
      "text"
    ],
    contextWindow: 131056,
    maxTokens: 32768,
    cost: {
      "input": 0.29,
      "output": 1.15,
      "cacheRead": 0.0725,
      "cacheWrite": 0
    },
  },
  "kimi-k2.7-code": {
    id: "kimi-k2.7-code",
    name: "Kimi K2.7 Code (NW Fast)",
    reasoning: true,
    compat: {
      "supportsReasoningEffort": false,
      "supportsDeveloperRole": false
    },
    input: [
      "text"
    ],
    contextWindow: 262128,
    maxTokens: 32768,
    cost: {
      "input": 0.95,
      "output": 4,
      "cacheRead": 0.2375,
      "cacheWrite": 0
    },
  },
  "kimi-k2.6": {
    id: "kimi-k2.6",
    name: "Kimi K2.6 (NW Fast)",
    reasoning: true,
    compat: {
      "supportsReasoningEffort": false,
      "supportsDeveloperRole": false
    },
    input: [
      "text"
    ],
    contextWindow: 262128,
    maxTokens: 32768,
    cost: {
      "input": 0.69,
      "output": 3.22,
      "cacheRead": 0.1725,
      "cacheWrite": 0
    },
  },
  "kimi-k2.6-fast": {
    id: "kimi-k2.6-fast",
    name: "Kimi K2.6 Fast (NW Fast)",
    reasoning: false,
    compat: {
      "supportsDeveloperRole": false
    },
    input: [
      "text"
    ],
    contextWindow: 262128,
    maxTokens: 32768,
    cost: {
      "input": 0.69,
      "output": 3.22,
      "cacheRead": 0.1725,
      "cacheWrite": 0
    },
  },
  "qwen3.5-397b": {
    id: "qwen3.5-397b",
    name: "Qwen3.5 397b (NW Fast)",
    reasoning: true,
    compat: {
      "supportsReasoningEffort": false,
      "supportsDeveloperRole": false
    },
    input: [
      "text"
    ],
    contextWindow: 262128,
    maxTokens: 32768,
    cost: {
      "input": 0.69,
      "output": 4.14,
      "cacheRead": 0.1725,
      "cacheWrite": 0
    },
  },
  "qwen3.5-397b-fast": {
    id: "qwen3.5-397b-fast",
    name: "Qwen3.5 397b Fast (NW Fast)",
    reasoning: false,
    compat: {
      "supportsDeveloperRole": false
    },
    input: [
      "text"
    ],
    contextWindow: 262128,
    maxTokens: 32768,
    cost: {
      "input": 0.69,
      "output": 4.14,
      "cacheRead": 0.1725,
      "cacheWrite": 0
    },
  },
  "glm-5.2": {
    id: "glm-5.2",
    name: "Glm 5.2 (NW Fast)",
    reasoning: true,
    thinkingLevelMap: {
      "minimal": null,
      "low": "high",
      "medium": "high",
      "high": "high",
      "xhigh": "max"
    },
    compat: {
      "supportsDeveloperRole": false
    },
    input: [
      "text"
    ],
    contextWindow: 1048560,
    maxTokens: 32768,
    cost: {
      "input": 1.45,
      "output": 4.5,
      "cacheRead": 0.3625,
      "cacheWrite": 0
    },
  },
  "glm-5.2-fast": {
    id: "glm-5.2-fast",
    name: "Glm 5.2 Fast (NW Fast)",
    reasoning: false,
    compat: {
      "supportsDeveloperRole": false
    },
    input: [
      "text"
    ],
    contextWindow: 1048560,
    maxTokens: 32768,
    cost: {
      "input": 1.45,
      "output": 4.5,
      "cacheRead": 0.3625,
      "cacheWrite": 0
    },
  },
  "glm-5.2-short": {
    id: "glm-5.2-short",
    name: "Glm 5.2 Short (NW Fast)",
    reasoning: true,
    compat: {
      "supportsDeveloperRole": false
    },
    input: [
      "text"
    ],
    contextWindow: 199984,
    maxTokens: 32768,
    cost: {
      "input": 1.45,
      "output": 4.5,
      "cacheRead": 0.3625,
      "cacheWrite": 0
    },
  },
  "glm-5.2-short-fast": {
    id: "glm-5.2-short-fast",
    name: "Glm 5.2 Short Fast (NW Fast)",
    reasoning: false,
    compat: {
      "supportsDeveloperRole": false
    },
    input: [
      "text"
    ],
    contextWindow: 199984,
    maxTokens: 32768,
    cost: {
      "input": 1.45,
      "output": 4.5,
      "cacheRead": 0.3625,
      "cacheWrite": 0
    },
  },
};
